name: CrystamaeHistoria
author: Sefiraat
description: A magical addon with a semi-technical slimefun feel allowing for the production of spells, gadgets and more.
main: io.github.sefiraat.crystamaehistoria.CrystamaeHistoria
website: https://github.com/Sefiraat/CrystamaeHistoria
version: ${project.version}
api-version: 1.20.6
depend:
  - Slimefun
softdepend:
  - mcMMO
  - ExoticGarden
  - SlimeTinker
  - HeadLimiter
  - Networks
  - WildStacker
  - RoseStacker
  - Netheopoiesis
commands:
  crystamaehistoria:
    description: /historia
    usage: /historia <sub>
    aliases: [ ch, hist ]